notes
bundle install
rake db:create db:migrate --trace

Error when testing in rails
uninitialized constant Mysql2::Client::FOUND_ROWS
cannot get it to work starting with fresh app
https://github.com/brianmario/mysql2/issues/959
Working in the repository
Solution Wrong version in gemfile which caused these issues

LoadError: cannot load such file -- mysql2/2.4/mysql2
this is caused by 2.4 not having the binarys added must revert to 2.3  or Installing RVM on Windows 10 to use multiple versions on one machine
this requires Cygwin Which acts like linux and windows cmd/terminal at the same time.

Does not work
Going back to repository for solution at later date.

Version AutoData2.2
is a shell to configure mysql

Reviewing 1.0 used scaffolding
There are controllers added
helpers
modles are added

zaxanllccom.mydomaincommysql.com

create an app on heroku
heroku create

heroku run rails db:migrate

git commit
git push heroku master
bcrypt issue
gem list bcrypt
gem uninstall bcrypt
gem install bcrypt --platform=ruby
repairs it
u = User.new(:userid => "myuserid", :password => "nate", :user_first_name => "test", :user_last_name => "testovich", :user_status => "mystatus", :user_type => "mytype")